# Generated by Django 3.0.7 on 2020-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200606_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_back',
            field=models.URLField(null=True),
        ),
    ]
