# Generated by Django 3.0.7 on 2020-06-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_project_link_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_back',
            field=models.URLField(default=True, null=True),
        ),
    ]
