# Generated by Django 3.0.7 on 2020-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200607_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_back',
            field=models.URLField(blank=True, null=True),
        ),
    ]
